### PR TITLE
Update Nigeria scraper

### LINKED ISSUE #552: Update nigeria_portal to download all the pages
http://nocopo.bpp.gov.ng/OpenData.aspx has now several pages

### PR DESCRIPTION
**Pull request by aguilerapy**
closes #552

### CODE REVIEW

**Comment by aguilerapy** [comment]
The scraper doesn't change the page, it stays in the first one so it downloads repeated files.

**Comment by jpmckinney** [comment]
The problem is that Scrapy by default clicks the first submit button, which is the search button. I'll push a commit that uses `clickdata` and `dont_click` to click the correct button.

**Comment by jpmckinney** [comment]
I think my commit also fixes the page 20 issue.

**Comment by jpmckinney** [comment]
Please test whether it reaches page 164.

**Comment by aguilerapy** [comment]
Successfully downloads to page 164.

**Review by yolile — APPROVED** [review]

**Review by yolile — APPROVED** [review]

**Pull request merged**
