### PR TITLE
print downloaded data location

### LINKED ISSUE #937: Add a message to explicitly state output location at the end of a crawl
Related to CRM-8186

A user was unable to intuit where the downloaded data was following a crawl. At the conclusion of successful crawls, we could output a message with the location.

I think it would be sufficient to state only the path relative to the user's working directory when running the scrapy command e.g. `Data is stored in a folder called "data" beneath where you ran the scrapy command`, however we could also consider the absolute path to be very explicit (I'm not a fan of this; this could get very long).

### PR DESCRIPTION
**Pull request by Ravf95**
Closes #937

### CODE REVIEW

**Comment by jpmckinney** [comment]
By disabling `STATS_DUMP`, the output becomes:

```
[a lot of messages]
2022-08-03 17:52:35 [scrapy.core.engine] INFO: Closing spider (finished)
2022-08-03 17:52:35 [cyprus_digiwhist] INFO: The download data has been stored in this directory data/cyprus_digiwhist/20220803_215231
2022-08-03 17:52:35 [scrapy.core.engine] INFO: Spider closed (finished)
```

If we don't disable it, then it looks like:

```
[a lot of messages]
2022-08-03 17:52:58 [scrapy.core.engine] INFO: Closing spider (finished)
2022-08-03 17:52:58 [cyprus_digiwhist] INFO: The download data has been stored in this directory data/cyprus_digiwhist/20220803_215254
2022-08-03 17:52:58 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 266,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 3973792,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'elapsed_time_seconds': 4.021908,
 'fileitem_count': 9214,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2022, 8, 3, 21, 52, 58, 562563),
 'item_scraped_count': 9214,
 'log_count/DEBUG': 9217,
 'log_count/INFO': 12,
 'log_count/WARNING': 3,
 'memusage/max': 86425600,
 'memusage/startup': 86425600,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2022, 8, 3, 21, 52, 54, 540655)}
2022-08-03 17:52:58 [scrapy.core.engine] INFO: Spider closed (finished)
```

The order can't be changed, unless we override the `STATS_CLASS` setting, and subclass the default statscollector, so that we write the FileStore directory after the stats – but this would require storing the directory on the spider itself (or similar), which breaks encapsulation somewhat.

The stats are relevant for debugging, as documented at https://kingfisher-collect.readthedocs.io/en/latest/logs.html#check-the-crawl-statistics So, I feel that we should leave them. The only downside is that the directory is a bit harder to see for less technical users, as it's a bit further up.

We can maybe just make it colored/bold text. We can use https://pypi.org/project/colorama/ for cross-platform support.

@yolile Do you have an opinion?

**Comment by yolile** [comment]
> @yolile Do you have an opinion?

I agree with you, we shouldn't disable `STATS_DUMP` as it adds important debugging info. We can use bold/colors as you suggest and/or use maybe some spaces around that message, e.g.

2022-08-03 17:52:58 [cyprus_digiwhist] INFO: -------------------FILES SAVED---------------
2022-08-03 17:52:58 [cyprus_digiwhist] INFO:
2022-08-03 17:52:58 [cyprus_digiwhist] INFO: **The downloaded data is available in data/cyprus_digiwhist/20220803_215254**
2022-08-03 17:52:58 [cyprus_digiwhist] INFO:
2022-08-03 17:52:58 [cyprus_digiwhist] INFO: ------------------------------------------------

**Comment by jpmckinney** [comment]
Good suggestion, to spare us another dependency (the markup for color/bold might also look weird when reading the log files on the web). I added a commit to make it look like:

```
2022-08-18 11:18:00 [scrapy.core.engine] INFO: Closing spider (finished)
2022-08-18 11:18:00 [cyprus_digiwhist] INFO: +------------------------- DATA DIRECTORY -------------------------+
2022-08-18 11:18:00 [cyprus_digiwhist] INFO: |                                                                  |
2022-08-18 11:18:00 [cyprus_digiwhist] INFO: | The data is available at: data/cyprus_digiwhist/20220818_151759  |
2022-08-18 11:18:00 [cyprus_digiwhist] INFO: |                                                                  |
2022-08-18 11:18:00 [cyprus_digiwhist] INFO: +------------------------------------------------------------------+
2022-08-18 11:18:00 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
```

**Comment by yolile** [comment]
Looks good to me! I thought we could maybe put this message at the beginning, but in `spider_opened` the message is even more lost because it is after all the `INFO: Enabled downloader middlewares:` logs

**Review by jpmckinney — APPROVED** [review]

**Pull request merged**
