### PR TITLE
[WIP] use treq instead of requests

### PR DESCRIPTION
**Pull request by yolile**
ref #292

### CODE REVIEW

**Comment by yolile** [comment]
@jpmckinney I was trying to use `treq.post` instead of `request.post` but, there is a problem. It seems like sometimes, if the file sent to kingfisher is big then the spider finished and is closed before the request is complete and I get:

> twisted.internet.task.TaskStopped
Unhandled error in Deferred:
2020-11-16 15:01:23 [twisted] CRITICAL: Unhandled error in Deferred:
Traceback (most recent call last):
Failure: twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.>]

And the other problem is that the `end_collection` request could be sent before all the `create_file` ones

**Comment by jpmckinney** [comment]
@yolile How did you test this? Just so we're using the same crawl command when debugging.

**Comment by jpmckinney** [comment]
Also, were you sending the requests to a local copy of Kingfisher Process that you were running?

**Comment by jpmckinney** [comment]
@yolile You have to return the deferreds :) (my latest commit). Please document in #292 why we need to call `str()` on booleans. The last thing to do is update tests to check for the log messages. You might need to use these helpers: https://treq.readthedocs.io/en/release-20.9.0/testing.html

**Comment by yolile** [comment]
@jpmckinney great! I was testing it with a local deployment of kingfisher and with `uruguay_releases -a sample=1` and with `canada_buyandsell`, both work now! I will update the remaining tests, and I already commented in #292 the reason why we use str and not booleans

**Comment by jpmckinney** [comment]
@yolile: I got the tests passing. I was trying to use async/await, but Twisted requires Awaitables to be converted to Deferreds, so I just used inlineCallbacks.

**Comment by jpmckinney** [comment]
We can improve the tests by using more of https://treq.readthedocs.io/en/release-20.9.0/testing.html (instead of stubbing treq.post), but if you can manually test the integration with KFP, I'm fine with leaving as-is.

**Comment by jpmckinney** [comment]
We could have gotten the tests to pass without `inlineCallbacks`. What was missing was a callback for treq.post, which would have returned the response: https://treq.readthedocs.io/en/release-20.9.0/#post

**Comment by jpmckinney** [comment]
Hmm, I'm realizing that we mock the return value of `treq.post` as a response object, but its real return value is a Deferred. 

Also, I'm not sure that https://treq.readthedocs.io/en/release-20.9.0/testing.html helps us. First, `StubTreq` doesn't support the files argument: https://treq.readthedocs.io/en/release-20.9.0/api.html#stubtreq-objects so we can't use it to test `create_file`. Secondly, it seems like the requests need to be directly consumed by the test, which would require adding hooks deep into our code.

**Comment by jpmckinney** [comment]
My latest commit reverts my changes in 56b9825812192a9a434686ec86af0da350a84374 and uses the pytest-twisted module to inline the callback *in the test* (my earlier commit inlined it in the extension, which was incorrect).

The tests require httpbin.org, which can fail unexpectedly. Unfortunately, vcrpy doesn't support Twisted (yet): https://github.com/kevin1024/vcrpy/issues/538

There might be a way to enable Scrapy's HttpCacheMiddleware in tests and store the results like vcrpy would.

**Comment by yolile** [comment]
@jpmckinney this looks great, and I tested it locally and works like a charm!

**Review by jpmckinney — APPROVED** [review]

**Pull request merged**
