### PR TITLE
Add KingfisherStoreFiles extension to avoid storing files in spiders

### LINKED ISSUE #277: Use item_scraped signal in extension, instead of writing files in spider
*Original issue title: Explore Item Exporters instead of bespoke system for writing items*

*Original issue description: I haven't had time to look at this closely, but on the surface it seems to do the same thing. Ideally, we can substitute Item Exporters without causing any change in behavior.*

https://docs.scrapy.org/en/latest/topics/exporters.html

### PR DESCRIPTION
**Pull request by yolile**
closes #277

### CODE REVIEW

**Comment by jpmckinney** [comment]
@yolile To address the issue you identified, can you add to `settings.py`:

```python
LOG_LEVEL = os.getenv('SCRAPY_LOG_LEVEL', 'INFO')
```

https://docs.scrapy.org/en/latest/topics/settings.html#log-level

**Comment by jpmckinney** [comment]
Actually, other DEBUG messages are useful (seeing which requests were retried, etc.). Let's instead add a custom log formatter, so that it excludes the OCDS data: https://docs.scrapy.org/en/latest/topics/logging.html#custom-log-formats

**Comment by yolile** [comment]
@jpmckinney I added all your suggestions (changing georgia and digiwhist_base spiders to be able to move `get_local_file_path_including_filestore` etc methods inside the store extension, FYI the georgia one wasn't working now anyway)
And also added a `post_to_api` field to the item to no post to kingfisher-process zip and tar files.
Also, I don't store the item if the item has the `number` attribute as this attribute is used when a big JSON file is sent to kingfisher-process as the behavior was to store only the original data.

**Comment by jpmckinney** [comment]
I did some refactoring and other cleanup. Looks good!

**Pull request merged**
