### PR TITLE
Add spider's docstring

### PR DESCRIPTION
**Pull request by aguilerapy**
ref #346

### CODE REVIEW

**Comment by yolile** [comment]
@jpmckinney the coverage here is failing due to the `checkall` command, should we add more tests for it?

**Comment by jpmckinney** [comment]
@yolile It's okay, I'll just change the sensitivity on Coveralls.

**Comment by jpmckinney** [comment]
I assume this is good to merge, if not for Coveralls blocking.

**Comment by yolile** [comment]
@jpmckinney yes, thank you!

**Pull request merged**
